# Generated by Django 4.1.1 on 2022-09-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_alter_song_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='song',
            table='demo_m_call',
        ),
    ]
