# Generated by Django 4.1.1 on 2022-09-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_alter_song_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='song',
            table=None,
        ),
    ]
